services:
  party0:
    image: integration-test:latest
    build: .
    environment:
      - RUST_BACKTRACE=1
    ports:
      - "8000:8000"
    command: >
      cargo test --test integration --features "test_helpers" -- 
        --party 0
        --port1 8000
        --port2 9000
        --docker
    tty: true
  party1:
    image: integration-test:latest
    build: .
    command: >
      cargo test --test integration --features "test_helpers" -- 
        --party 1
        --port1 9000
        --port2 8000
        --docker
    tty: true
