services:
  party0:
    image: ark-mpc-integraton:latest
    build:
      context: ..
      dockerfile: integration/Dockerfile
    environment:
      - RUST_BACKTRACE=full
    ports:
      - "8000:8000"
    command: >
      cargo run --release -- 
        --party 0
        --port1 8000
        --port2 9000
        --docker
    tty: true
  party1:
    image: ark-mpc-integraton:latest
    environment:
      - RUST_BACKTRACE=full
    ports:
      - "9000:9000"
    command: >
      cargo run --release -- 
        --party 1
        --port1 9000
        --port2 8000
        --docker
    tty: true
